name = "TransitionZoneDeformation"
uuid = "1e7477b4-183e-480b-857d-999595e3b56d"
version = "1.0.0-DEV"
authors = ["Josiah <josiah.s.murray.work@gmail.com> and contributors"]

[deps]
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
SpatialLaplaceInversion = "ade9c3b6-7041-42de-a1bd-cf2d0a5b18b8"

[sources]
SpatialLaplaceInversion = {rev = "main", url = "https://github.com/Josiah-Murray/SpatialLaplaceInversion.git"}

[compat]
PolynomialRoots = "1.1.0"
SpatialLaplaceInversion = "1.0.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
